version: "3"
services:
  app:
    build: .
    image: fastapisql:v0.1
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=fastapisql
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
volumes:
  postgresdata: