version: "3"
services:
  app:
    image: nadnan18/fastapisql:latest
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE=${DATABASE}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRATION_MINUTES=${ACCESS_TOKEN_EXPIRATION_MINUTES}
    ports:
      - 80:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5