name: Build and Deploy
run-name: ${{ github.actor }} is learning Github Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # tags:
    #   - v*
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installing dependencies
        run: python -m pip install --upgrade pip && \
          python -m pip install -U pipenv && \
          python -m pipenv install --ignore-pipfile

      - name: running tests
        run: python -m pipenv run pytest
