name: Build and Test
run-name: ${{ github.actor }} is learning Github Actions
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    environment:
      name: test_env_variables
    env:
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTES}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE: ${{secrets.DATABASE}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      TEST_DATABASE_PORT: ${{secrets.TEST_DATABASE_PORT}}
      TEST_DATABASE: ${{secrets.TEST_DATABASE}}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.TEST_DATABASE}}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installing dependencies
        run: pip install --upgrade pip && pip install pipenv && pipenv install --system --deploy --ignore-pipfile --dev

      - name: running tests
        run: pipenv run pytest -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapisql:latest
  test-deployment:
    environment:
      name: test_env_variables
    runs-on: self-hosted
    steps:
      - name: Manage Docker Secrets
        run: |
          
          sudo rm -rf /tmp/secrets.txt
          
          echo ALGORITHM=${{secrets.ALGORITHM}} >> /tmp/secrets.txt
          echo ACCESS_TOKEN_EXPIRATION_MINUTES${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTES}} >> /tmp/secrets.txt
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> /tmp/secrets.txt
          echo DATABASE_USER=${{secrets.DATABASE_USER}} >> /tmp/secrets.txt
          echo DATABASE_HOST=${{secrets.DATABASE_HOST}} >> /tmp/secrets.txt
          echo DATABASE_PORT=${{secrets.DATABASE_PORT}} >> /tmp/secrets.txt
          echo DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} >> /tmp/secrets.txt
          echo DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} >> /tmp/secrets.txt
           
      - name: Close service if it exists
        run: |
          if docker service inspect fast-app &> /dev/null; then
            echo "Service exists"
            echo "Deleting service"
            docker service rm fast-app
          else
            echo "No such service exists"
          fi
           
      - name: Deploy to Docker Swarm
        run: |
          docker service create --name fast-app --network defstack_default \
          --secret source=/tmp/secrets.txt, target=/app/.env \
          --publish published=8080,target=80 \
          $DOCKERHUB_USERNAME/fastapisql:latest
