name: Build and Deploy
run-name: ${{ github.actor }} is learning Github Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # tags:
    #   - v*
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout main
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo -H pip install -U pipenv && \
          python3 -m pipenv install --system --deploy --ignore-pipfile

      - name: running tests
        run: pytest
