name: Build and Deploy
run-name: ${{ github.actor }} is learning Github Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # tags:
    #   - v*
jobs:
  job1:
    environment:
      name: test_env_variables
    env:
      ALGORITHM: ${{ALGORITHM}}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${{ACCESS_TOKEN_EXPIRATION_MINUTES}}
      SECRET_KEY: ${{SECRET_KEY}}
      DATABASE_USER: ${{DATABASE_USER}}
      DATABASE: ${{DATABASE}}
      DATABASE_HOST: ${{DATABASE_HOST}}
      DATABASE_PORT: ${{DATABASE_PORT}}
      DATABASE_PASSWORD: ${{DATABASE_PASSWORD}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installing dependencies
        run: pip install --upgrade pip && pip install pipenv && pipenv install --system --deploy --ignore-pipfile --dev

      - name: running tests
        run: pipenv run pytest -v
