name: Pull and Deploy
run-name: ${{ github.actor }} is learning Github Actions
on:
  create:
    tags:
      - v*
    branches:
      - main
jobs:
  deploy:
    environment:
      name: prod_secrets
    env:
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTES}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE: ${{secrets.DATABASE}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
    runs-on: self-hosted
    steps:
      - name: Delete old docker container
        run: sudo docker rm -f fast-app || true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pull image
        run: docker pull ${{secrets.DOCKERHUB_USERNAME}}/fastapisql:latest
          
      - name: Run docker
        run: |
          docker run -d --name fast-app --network nabnetwork -h 0.0.0.0 -p 8000\
          -e ALGORITHM="${ALGORITHM}" \
          -e ACCESS_TOKEN_EXPIRATION_MINUTES="${ACCESS_TOKEN_EXPIRATION_MINUTES}" \
          -e SECRET_KEY="${SECRET_KEY}" \
          -e DATABASE_USER="${DATABASE_USER}" \
          -e DATABASE="${DATABASE}" \
          -e DATABASE_HOST="${DATABASE_HOST}" \
          -e DATABASE_PORT="${DATABASE_PORT}" \
          -e DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
          -e DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME}" \
          -e DOCKERHUB_TOKEN="${DOCKERHUB_TOKEN}" \
          ${{secrets.DOCKERHUB_USERNAME}}/fastapisql:latest