name: Build and Deploy
run-name: ${{ github.actor }} is learning Github Actions
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: prod_secrets
    env:
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRATION_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRATION_MINUTES}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE: ${{secrets.DATABASE}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapisql:v0.1
          cache-from: type=registry,ref=user/fastapisql:v0.1
          cache-to: type=inline

      - name: Pulling Image
        run: docker pull nadnan18/fastapisql:v0.1

      - name: Delete Old Image
        run: docker rm -f fastapisql || true

      - name: Run New Docker Image
        run: docker run -d --name fastapisql nadnan18/fastapisql:v0.1
